name: openeo-r-udf
channels:
- conda-forge
dependencies:
- python=3.7
- r-base
- libgdal
- gdal
- geos
- proj
- pip
- requests
- numpy
- xarray
- rpy2
- r-stars
- r-lubridate
- r-jsonlite
- dask
- distributed
- r-curl
- libnetcdf
- netCDF4
- h5netcdf
- pip:
  - openeo_r_udf
